global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'websocket-server'
    static_configs:
      - targets: ['websocket-server:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    
  - job_name: 'websocket-health'
    static_configs:
      - targets: ['websocket-server:8081']
    scrape_interval: 30s
    metrics_path: /metrics
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']